### ISSUE TITLE
Create hello world application

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/app-android#1]

**Comment by divayprakash** [comment]
@shakeelmohamed Sorry about the delay, just got caught up with schoolwork.

I've finally got some time on my hands now, and so am beginning with this project. Just wanted to ask you, what API level are we looking to support. As you can see [here](https://developer.android.com/about/dashboards/index.html#Platform) API level 21 (Lollipop) and up gives us 50.7% of devices running Android. However, going down to API 20 (KitKat) boosts that significantly to 79.9%.

**Comment by shakeelmohamed** [comment]
@divayprakash I'm good with Kitkat

**Comment by BhaveshSGupta** [comment]
I can take this one!!

**Comment by shakeelmohamed** [comment]
@BhaveshSGupta see #3, this is in progress
